language: node_js
node_js:
  - node
services:
  - mongodb
install:
  - npm run install-all
before_script:
  - npm install -g serverless
  - sleep 15
script:
  - npm run test
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
