language: node_js
node_js:
  - node
services:
  - mongodb
before_script:
  - npm install -g serverless
  - sleep 15
script:
  - npm run test
deploy:
  provider: script
  script: cd client/collab-story && npm run build && cd ../.. && serverless deploy
  skip_cleanup: true
